version: "3"

services:
  postgres: 
    image: postgres:12
    restart: always
    container_name: postgres
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twitter_database
    volumes: 
      - "./postgres-data:/var/lib/postgresql/data"